---

- name: Install common desktop packages
  apt: 
    pkg: ['bleachbit', 'easytag', 'byzanz', 'geany', 'libnotify-bin', 'inotify-tools', 'meld', 'cifs-utils', 'mpv', 'pinta', 'rhythmbox', 'rxvt-unicode-256color', 'sox', 'tilda', 'ubuntu-restricted-extras', 'vlc', 'wmctrl', 'xclip', 'xdotool']
    state: latest
    update_cache: yes 
    cache_valid_time: "{{ aptcachetime }}"

    #- easytag # audio files metadata management
    #- byzanz # screen recording
    #- meld # Diff / merge tool
    #- pinta # light paint.net equivalent
    #- sox # to play sounds
    #- tilda # lighter than guake
    #- ubuntu-restricted-extras # MP3, Microsoft fonts, Flash plugin, LAME and DVD playback
    #- wmctrl # to control windows
    #- xclip # to manipulate the clipboard
    #- xdotool # to control windows
