---

- name: Check if TeamViewer is installed
  command: dpkg-query -W teamviewer
  register: teamviewer_check_deb
  failed_when: teamviewer_check_deb.rc > 1
  changed_when: teamviewer_check_deb.rc == 1

- name: Install TeamViewer dependencies
  apt: 
    pkg: ['libjpeg62', 'libxinerama1', 'libxrandr2', 'libxtst6']
    state: latest 
    update_cache: yes 
    cache_valid_time: "{{ aptcachetime }}"

- name: Download TeamViewer
  get_url: url="https://download.teamviewer.com/download/linux/teamviewer_amd64.deb" dest="/tmp/download-teamviewer-latest.deb"
  when: teamviewer_check_deb.rc == 1

- name: Install TeamViewer
  apt: deb="/tmp/download-teamviewer-latest.deb"
  when: teamviewer_check_deb.rc == 1

- name: Clean TeamViewer deb file
  file: path=/tmp/download-teamviewer-latest.deb state=absent
