---

- name: Configure the Oracle APT key
  apt_key: 
    url: https://www.virtualbox.org/download/oracle_vbox.asc 
    state: present

- name: Install VirtualBox latest 
  apt: 
    pkg:  virtualbox
    state: present
