---

  - name: Install git
    apt: 
      pkg: git-core
      state: present
      update_cache: yes 
      cache_valid_time: "{{ aptcachetime }}"

  - name: Adding lg alias for git
    copy: 
      src: gitconfig
      dest: "{{ ansible_env.HOME }}/.gitconfig" 
      owner: "{{ ansible_env.USER }}" 
      group: "{{ ansible_env.USER }}"
      mode: 644
      backup: yes
