---

- name: Install requirements
  apt: 
    pkg: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    state: latest 
    update_cache: yes

- name: Installing apt-key
  apt_key: 
    id: "9DC858229FC7DD38854AE2D88D81803C0EBFCD88" 
    url: https://download.docker.com/linux/ubuntu/gpg 
    state: present

- name: Add deb repository
  apt_repository: 
    repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable' 
    state: present

- name: Install
  apt: 
    pkg: ['linux-image-extra-virtual', 'docker-ce'] 
    state: latest 
    update_cache: yes

- name: Create Docker group
  group: 
    name: docker 
    state: present

- name: Add current user to Docker group
  user: 
    name: "{{ ansible_env.USER }}" 
    groups: docker 
    append: yes

- name: "Ensure Docker is {{ docker.start | ternary('started','stopped') }}"
  service: 
    name: docker 
    state: "{{ docker.start | ternary('restarted','stopped') }}" 
    enabled: "{{ docker.service_enabled }}"

- name: Install docker-compose
  get_url: 
    url: "https://github.com/docker/compose/releases/download/{{ docker.docker_compose_version }}/docker-compose-Linux-x86_64" 
    dest: /usr/local/bin/docker-compose 
    force: no 
    mode: 0755
